services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: always
    env_file:
        - src/.env
    expose:
        - 5432
    volumes:
        - ./dbs/postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready -U app -d auth" ]
      interval: 10s
      timeout: 3s
      retries: 3
  
  redis:
    image: redis:7.4.0
    container_name: redis
    restart: always
    env_file:
        - src/.env
    expose:
        - 6379
    volumes:
        - redis_data:/data/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2s
      timeout: 60s
      retries: 5
  
  auth:
    container_name: auth
    build: src
    env_file:
      - src/.env
    restart: always
    command: bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
      - redis
  
  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config:/etc/nginx/conf.d:ro
    depends_on:
      - auth

volumes:
  postgres_data:
    name: postgres_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbs/postgres-data
  redis_data:
    name: redis_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dbs/redis-data