FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /app

WORKDIR /app/

COPY tests tests/


RUN pip install --no-cache-dir --upgrade pip
RUN pip install -r /app/tests/functional/requirements.txt