version: '3'

services:
  db:
    image: postgres:16.1
    container_name: movies_db
    restart: always
    env_file:
        - app/.env
    volumes:
        - ./dbs/postgresql-data:/var/lib/postgresql/data

  service:
    image: movies_image
    container_name: movies
    build:
      context: app
    env_file: app/.env
    volumes:
      - ./app/static:/opt/app/static/
      - ./app/media:/opt/app/media/
    depends_on:
            - db
    restart: always

  nginx:
    image: nginx:1.25.5
    container_name: movies_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./app/static:/var/www/static/
      - ./app/media:/var/www/media/
    depends_on:
      - service

  redis:
    image: redis
    container_name: movies_redis
    restart: always
    volumes:
        - ./dbs/redis-data:/data/