version: '3'

services:
  db:
    image: postgres:16.1
    container_name: movies_db_local
    restart: always
    env_file:
        - app/.env
    ports:
      - 5454:5432
    volumes:
        - ./dbs/postgresql-data:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: movies_redis
    restart: always
    ports:
        - 6380:6379
    volumes:
        - ./dbs/redis-data:/data/
